#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MoodStreamer.Resource", IsApplication=true)]

namespace MoodStreamer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MoodStreamer.Shared.Resource.String.ApplicationName = global::MoodStreamer.Resource.String.ApplicationName;
			global::MoodStreamer.Shared.Resource.String.Hello = global::MoodStreamer.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int info = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int next = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int pause = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int play = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int testsquare = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080011
			public const int action_logout_button = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int action_playing_button = 2131230738;
			
			// aapt resource value: 0x7f080010
			public const int action_settings = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int action_viewstats = 2131230739;
			
			// aapt resource value: 0x7f080008
			public const int artWorkImageView = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int backButton = 2131230729;
			
			// aapt resource value: 0x7f08000f
			public const int cacheCheckbox = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int lastfmPasswordEdit = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int lastfmUsernameEdit = 2131230733;
			
			// aapt resource value: 0x7f080003
			public const int loginRegisterButton = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int logo = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int nextButton = 2131230731;
			
			// aapt resource value: 0x7f080002
			public const int passwordBox = 2131230722;
			
			// aapt resource value: 0x7f08000a
			public const int playPauseButton = 2131230730;
			
			// aapt resource value: 0x7f080007
			public const int playerRelLayout = 2131230727;
			
			// aapt resource value: 0x7f08000c
			public const int scrobbleCheckBox = 2131230732;
			
			// aapt resource value: 0x7f080006
			public const int square = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int startPlaying = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int textView2 = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int usernameBox = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Player = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int main_activity_actions = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int calmExcitedLabel = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int happyButtonText = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int howareyoufeeling = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int loginRegisterText = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int positivityLabel = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int preferencesName = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int sadButtonText = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int startPlayingText = 2131034119;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Preference = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
