#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MoodStreamer.Resource", IsApplication=true)]

namespace MoodStreamer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MoodStreamer.Shared.Resource.String.ApplicationName = global::MoodStreamer.Resource.String.ApplicationName;
			global::MoodStreamer.Shared.Resource.String.Hello = global::MoodStreamer.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int transition_animation = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backwhite = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int disagree = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dot = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int info = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int infowhite = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int monoandroidsplash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int next = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int nextwhite = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int pause = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int pausewhite = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int play = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int playwhite = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int sadwhite = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int testsquare = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int vol = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001c
			public const int action_disagree = 2131296284;
			
			// aapt resource value: 0x7f090019
			public const int action_logout_button = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int action_playing_button = 2131296282;
			
			// aapt resource value: 0x7f090018
			public const int action_settings = 2131296280;
			
			// aapt resource value: 0x7f09001b
			public const int action_viewstats = 2131296283;
			
			// aapt resource value: 0x7f09001d
			public const int action_vol = 2131296285;
			
			// aapt resource value: 0x7f09000a
			public const int artWorkImageView = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int artworkLayout = 2131296265;
			
			// aapt resource value: 0x7f09000c
			public const int backButton = 2131296268;
			
			// aapt resource value: 0x7f090017
			public const int cacheCheckbox = 2131296279;
			
			// aapt resource value: 0x7f090007
			public const int dot = 2131296263;
			
			// aapt resource value: 0x7f09000f
			public const int emailBoxRegister = 2131296271;
			
			// aapt resource value: 0x7f090016
			public const int lastfmPasswordEdit = 2131296278;
			
			// aapt resource value: 0x7f090015
			public const int lastfmUsernameEdit = 2131296277;
			
			// aapt resource value: 0x7f090003
			public const int loginButtonLoginActivity = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int logo = 2131296256;
			
			// aapt resource value: 0x7f09000e
			public const int nextButton = 2131296270;
			
			// aapt resource value: 0x7f090012
			public const int passwordAgainBox = 2131296274;
			
			// aapt resource value: 0x7f090002
			public const int passwordBoxLogin = 2131296258;
			
			// aapt resource value: 0x7f090011
			public const int passwordBoxRegister = 2131296273;
			
			// aapt resource value: 0x7f09000d
			public const int playPauseButton = 2131296269;
			
			// aapt resource value: 0x7f090008
			public const int playerRelLayout = 2131296264;
			
			// aapt resource value: 0x7f09000b
			public const int playerSeek = 2131296267;
			
			// aapt resource value: 0x7f090004
			public const int registerButtonLoginActivity = 2131296260;
			
			// aapt resource value: 0x7f090013
			public const int registerButtonOnRegisterActivity = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int scrobbleCheckBox = 2131296276;
			
			// aapt resource value: 0x7f090006
			public const int square = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int textView2 = 2131296261;
			
			// aapt resource value: 0x7f090001
			public const int usernameBoxLogin = 2131296257;
			
			// aapt resource value: 0x7f090010
			public const int usernameBoxRegister = 2131296272;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Player = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RegisterLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main_activity_actions = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int player_activity_actions = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int calmExcitedLabel = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int happyButtonText = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int howareyoufeeling = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int loginText = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int positivityLabel = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int preferencesName = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int registerText = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int sadButtonText = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int startPlayingText = 2131099655;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Mono_Android_Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int Preference = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
