#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MoodStreamer.Resource", IsApplication=true)]

namespace MoodStreamer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MoodStreamer.Shared.Resource.String.ApplicationName = global::MoodStreamer.Resource.String.ApplicationName;
			global::MoodStreamer.Shared.Resource.String.Hello = global::MoodStreamer.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int next = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int pause = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int play = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000e
			public const int action_settings = 2131165198;
			
			// aapt resource value: 0x7f07000a
			public const int artWorkImageView = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int backButton = 2131165195;
			
			// aapt resource value: 0x7f070007
			public const int calmExcited = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int loginRegisterButton = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int logo = 2131165184;
			
			// aapt resource value: 0x7f07000d
			public const int nextButton = 2131165197;
			
			// aapt resource value: 0x7f070002
			public const int passwordBox = 2131165186;
			
			// aapt resource value: 0x7f07000c
			public const int playPauseButton = 2131165196;
			
			// aapt resource value: 0x7f070005
			public const int positiveNegative = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int startPlaying = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int textView1 = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int textView2 = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int theView = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int usernameBox = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Player = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int main_activity_actions = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int calmExcitedLabel = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int happyButtonText = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int loginRegisterText = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int positivityLabel = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int sadButtonText = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int startPlayingText = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
